language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: sodglxiu1PudtxcJhDQMaBf2weWWYknW+UiODULst3WUudzJmElBtv8WcJHF1gbZXO0+M0ikyuR3CvZgdeel5YDQq6C54LCgvqTPtfk3N1cvb4wlphV1w5vTiPfx8oMBHiaE9wyNOGcI9m72bAH4l22UtUMhAazBXXW54upk8WLidT8qoF7lE1fa/oE4ZBHeCwxwJb4d4ioidvy/zimMsx7g7/wm6JYcDBj0K20imy7AXHkqtTvxz4CYGFlgTL4o4GiYBZ4sqiljXTZDG7xEl6RIKTAGtvfNVUEVh8pdNAHPjOd+2oLMuYmLnlJcXNMrzaU8YtPoBL1aAuV3EEHvkF/o04AO15l3DhWYPB+NZ5m37K2ASNGwjRklk4kpgVGsD1S8hUEEITjOffJag7GVRBCn7ANTOQbZoZ/+MPI2I1Hcf9VBzfBH3N0X92tr5uYpH42VE4nIrAKS8wjKIyU/yXQU639e2KMu1fZOJXPs1S8+cjbQa8Cm+xTpwSydV5EduLCK0eGqzbK0YpPnOt2r3KWdYVVyMYvTGTkeHk3Yw7mbHyH3uQIxf3+Tx/jh3+iAN170MOvyjJ4zrDF4cbJw9rV+8C9+grPpZ621JLvOrwzyhFnhjM1In3RBzYGgw4wldkBnPTheXF/RMw13GLShiaD/5odO8P/RfNteZ+It4tA=
  app: floating-spire-97225
  on:
    repo: PiedPiperInc/TicTacToe
