language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: iWwiBfTPKM0T7PXQn4VTzAWwvySkjsYIdr7NDP9EVqmQ6eq6BUczrnOrKZt3i5l5tK7A5FaB5dHXS3URkUvi9eD3VrWGNGceqaUrxXsyLRLc5h4D0195iWMppMBoUO3SH5XNj/H6OuL7i1046m7r9OO554jOIlKQvlvj05RsnRL38v6tTM1KnDUdebyAXZFLIOSF32a6JPrp9wwFc5G3N95EsEXADnV3Scr+DJ0/6AsnYDO4t92PTxteZ8+s1iA+rPFpn5SjrSy45RyaX9R//AY0CxFZmno8IlmIZ+BKJX92S5tSnRF/7RrZyezaiwsCCOedWymKftLuLcy4FmE+ZLSIP6UiiekGebcCtnKEEKWxbNo/AyqdMZhOI39O6gua4szF0hSevYKBdDO90q0F2ElySnUCt2ASJcIIlS7YxZ+GNvzBNuyF6k0y5X2ahu2bKL6DC5CsdW+o2OqZMbuXHP443Ona/n05dHHNSNEBsoVNg0oKP7Pl20EKdb9q2BY4n5mQFO2FpBqf4JYjvMzZG4JNOr2oFpegogKvm+wdbVlB+ctrVRFvhRxGQ78XNW+jhTQysBoPFqYisd/TGYLuXv6gmedtWLHURKwjC1LK2Jle4/1BfpJ+VFYDjaxSNSA3BCO5zgy0s0MEljHtzDBNCRgK1V+GztVwZY45mQNwhH4=
  app: floating-spire-97225
  on:
    repo: PiedPiperInc/TicTacToe
