language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ATY1WBDMUb4hLVF0uZji8pyB+PyuOOtQvJCoBVIRvcMb3/ncBnII0U8S3tji5YMc0hCHbqM+sVtmR0rQyJE1tTo196Muj4b5lgtTEEYaSMGxSsNi/6UqyPn3WR4/oB3K0Wpl2zpJE3bHi15EHy0m0fNHTsPwGvDyW2sN0MgeSlf7qHZ7HdDiOsTlG5o0okhpwl+RaFdVkqCMBwCl12ydTjj5sVVu4eGmyKN456Gk6DAZMYhKpIsqdVZJnQ+qdf3d3FbfJw7P+hPruv9VVAWh6PLSca0ep2FGFlz/3nWNlEWEqz7ENSTEjcrSa7+C0CAbUVQ8ad3R1Je4wYpfszlgRVQI/bWBg6PfOM3iIeYpmpebinmPertQ2m8GxPbdHX482tMvG9NEvtvy9n7wWJ3rDtE70KPbP8T+RpoHI4a4wcuyQwEIkeYFX8ftNa0yn8B4zWgyaQDkz+zwxe1NZmRPRVQclvs8XmZRejwkyQnkCsWLrSrA4L+6Av3Mki27zmalcjVaDURoQs1sCXHWlFxcZsYPxS/QacW4/CVnxy0BwXs8D8AK5Xtyi34l2GDxU4ak9L6ysVIWWKkGTPKLRQrf/KT7AiUpKO/LNpopPbqmhSKBC9KjPBSQEelIyGe74s2pILIpnmWA6zzaadIraa6l/V18QFritxJ+GgAE9w7T/xk=
  app: TicTacToe
  on:
    repo: PiedPiperInc/TicTacToe
