language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: cog52UvXqvMrbXA9z2W7oCthFSILU1ypTh4NheWtvr4sxgoLcx6W97Rm+82ETto6EZnRJFPae9TSVy1j6Z8De1LySY5gj0GGbyuDL6WyjYA3NOkiY4U7BZ4AIKoTesfUFb2TYAezZZNFCkLahhx2rZGz5bR56qv0EstHllmRXs/gruN517O5lvRCYD3KeBE5xWTRjjlk99hQpa3WMwbi5iDzyBstGo+xQuBfmee/WOg8QXfAvtd+5jQM0xbMRl3KlvbqIXgrvAK/O3ONs9ZABKAZCcaULLtZTWfuFmIQ5T0k4B2AC28oSqGy6wkT64gDGf/+IUl3WM8XtY32kzFWMtD6Avl2WBI7VcXMP9lK8wCKUrydA0Vt+h+P0MsOv+bRZbV2lkKBLNbZ9QK+LXaEg1c6CS8+nwywIFiqlNbrCMN3vQm/eKrvYk33QH+BZjOe/55YzQHkwELsApGbn9NGcYrb5FG4e7q0b2tEYR/Mv9Mj2LNyO557Orq+yU68e8K7/QRWh0XJYM0ZN5pNTTSXK7XkCOvuaUJkFwZJzlYSp692CNeZo7lvj0cYc6HbZysrFa/vq7xITfHoakvvSA5Us3XkIdO5YQfClwR0dR6gX96k5jnUy6v1wNL3Cq55BSASj5OC0pvdtd8ln2tCkksuDd+nw9ktkNOqhitVjLx9jJw=
