language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GhCpTxYs9XxZUWYJvycg/XTLKM1ENDyNvmgvv/V82TaUgXWT/X75gnNNec8O8tBHhgpuqqm+o0ywCMzuetmJdAx4pbkng1ZVvQsy9/x16TDx5QZJGorR+SewFJboymzEzA3BfnWmrOUpiYlH/5kubEt8AROvFivsvcQCVvl60YA1914NuQ0b60VU3wYl5X045fj0imBSPpPEqbdj2nsoJ9+7TDvKIxjvey3rA+ISdSXwGJ0fVn9E7PLwEyBiffGpr1dXSWaab6NABYxoTNx2+bjUFSzStHEgkFXLDiiN69sml150A4LpeFC1h0pnpeTVKlAkirl5FCeVDq6BQDkH2i969LTm2FuWKPpZwksOl9f/S4I9orQ+wb+bCXS1+ixY/C9vWfXFw6GBtNK9ZQ89B1MlVCLDk2Y8y8EYlAKjD3792+exH/IB8pZitfS2uQ5Uiwpb086EvdbyJIVAtnDqtRQICVP4+446flH9ATbQ4sqivhBahq+b97A3G05WjrebhgTqcTofp57Pjm5Qbx3NyfGodRI8+Ho/NbCBjyLth/AQquuIM9hctx1rqzoxrwzAeqU7zFRJDkmyJDdmcVeTibSWCvcPBdwykRyGKAiPgldNd9CT2N9bufd5blitLi3Adomwm+XoRqwK08S20kb9BqJsN15qE+RBIM4ABBzu9tc=
  app: powerful-eyrie-38639
  on:
    repo: PiedPiperInc/TicTacToe
    branch: webApp
